### ISSUE TITLE
Homepage hashtag field does not load correctly in firefox

### ISSUE THREAD

**Issue by zippynk** [PartySync/web#4]
The field is still there, and you can still type text in it, but you can't see what you're typing.
The hashtag still displays, but the "JOIN ROOM" does not.

Works in Chromium on the same computer, so it only seems to be a problem with Firefox and related browsers.
The configuration that produced the bug: MacOS Macintosh X 10.10, Firefox 35.0, Flash 16.0 (release 0)
The configuration that did not produce the bug: MacOS Macintosh X 10.10.0, Chrome (actually Chromium, but I guess the User Agent shows Chrome) 42.0.2293.0, No Flash version detected

**Comment by gmittal** [comment]
This seems to be an issue with the Firefox Developer Edition. This does not seem to be a problem on the standard edition of Firefox.


http://puu.sh/gEjFA/79727db30b.png

**Comment by zippynk** [comment]
It's still happening for me in regular Firefox, but I have several extensions which each cause certain websites to behave weirdly. What version numbers of Firefox and Firefox Dev Edition did you use to create that screenshot?

**Comment by gmittal** [comment]
Fixed the issue by getting rid of the hashtag altogether.
