### ISSUE TITLE
Video shows related videos view when ending

### ISSUE THREAD

**Issue by zippynk** [PartySync/web#5]
The last video in the queue will show related videos afterwards, but these related videos will not be added to the queue, even if they are selected.

**Comment by zippynk** [comment]
Not sure how this affects other browsers.

**Comment by gmittal** [comment]
This is not that big of a concern at the moment, because if somebody else adds something to the queue, the video player will automatically start itself up again, and stop the related video that the user is watching and continue playing the videos within the queue.
