### ISSUE TITLE
Firefox compatibility issues

### ISSUE THREAD

**Issue by gmittal** [PartySync/web#6]
Some of the UI breaks in Firefox, and it looks unpleasant and feels unpleasant to use.

Fix ASAP.

**Comment by zippynk** [comment]
Video playback doesn't work at all for me.

**Comment by gmittal** [comment]
Some of the issue has to do with the fact that sometimes the YT Player API fails to load, which is often caused by page load times and other external scripts. I have cleared some of that stuff up.
